

name:Python application

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  review:

    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -uses: actions/python@v4
      with:
        python-version: "3.10"
      -name: Install dependencies
        run:
          pip install -r requirements.txt
      -name: Run code Review
        run: |
          python ./scripts/review.py